// File generated by FlutterFire CLI.
// TODO: Run FlutterFire CLI to generate proper firebase_options.dart for delivery_manager app
// For now, using driver app configuration as a placeholder
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7y0_tdNWtiOswJ1xWR8PP8lT_R_jzQuQ',
    appId: '1:279573864228:web:58d7a3f52330f843369db1',
    messagingSenderId: '279573864228',
    projectId: 'delivery-cfbae',
    authDomain: 'delivery-cfbae.firebaseapp.com',
    storageBucket: 'delivery-cfbae.firebasestorage.app',
    measurementId: 'G-MR39Q5BTHB',
  );

  // TODO: Replace these with manager app Firebase configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwsMXNSjfqMsLvodPty06NGp6Ynj9AVIU',
    appId: '1:279573864228:android:92bb03a6776d44f0369db1',
    messagingSenderId: '279573864228',
    projectId: 'delivery-cfbae',
    storageBucket: 'delivery-cfbae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRg-89cVThajDetXB44PIPA_b6XBtFIxo',
    appId: '1:279573864228:ios:d01a3c9c946f452a369db1',
    messagingSenderId: '279573864228',
    projectId: 'delivery-cfbae',
    storageBucket: 'delivery-cfbae.firebasestorage.app',
    androidClientId: '279573864228-66o617n808dtpfo4qfui4lef1jinjm4g.apps.googleusercontent.com',
    iosClientId: '279573864228-r17626mv2iqsde7dv23l9k173th38kru.apps.googleusercontent.com',
    iosBundleId: 'website.sofistem.deliveryManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOn_ua5cy_3KeGID6gcKNpy0Iv67EsRh0',
    appId: '1:279573864228:web:dd73e86c32f6888a369db1',
    messagingSenderId: '279573864228',
    projectId: 'delivery-cfbae',
    authDomain: 'delivery-cfbae.firebaseapp.com',
    storageBucket: 'delivery-cfbae.firebasestorage.app',
    measurementId: 'G-9QQKJFQ1EZ',
  );

}